# Generated by Django 5.1.1 on 2024-11-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanieAeriana',
            fields=[
                ('id_companie', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(choices=[('Tarom', 'Tarom'), ('BlueAir', 'BlueAir'), ('WizzAir', 'WizzAir'), ('RyanAir', 'RyanAir'), ('Lufthansa', 'Lufthansa'), ('TurkishAirlines', 'TurkishAirlines'), ('AirFrance', 'AirFrance'), ('Qatar', 'Qatar')], max_length=50)),
                ('an_infiintare', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sediu', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeronava',
            fields=[
                ('id_aeronava', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('capacitate', models.PositiveIntegerField()),
                ('an_fabricatie', models.DateField()),
                ('disponibilitate', models.BooleanField()),
                ('companie_aeriana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeroport.companieaeriana')),
            ],
        ),
        migrations.CreateModel(
            name='Zbor',
            fields=[
                ('id_zbor', models.AutoField(primary_key=True, serialize=False)),
                ('plecare', models.CharField(max_length=50)),
                ('destinatie', models.CharField(max_length=50)),
                ('data_plecare', models.DateField()),
                ('ora_plecare', models.TimeField()),
                ('data_sosire', models.DateField()),
                ('ora_sosire', models.TimeField()),
                ('aeronava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeroport.aeronava')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id_rezervare', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('data_rezervare', models.DateField()),
                ('zbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeroport.zbor')),
            ],
        ),
        migrations.CreateModel(
            name='EchipajdeBord',
            fields=[
                ('id_echipaj', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('data_nastere', models.DateField()),
                ('prenume', models.CharField(max_length=50)),
                ('functie', models.CharField(choices=[('pilot', 'Pilot'), ('copilot', 'Copilot'), ('insotitor', 'Insotitor de zbor')], max_length=50)),
                ('companieaeriana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeroport.companieaeriana')),
                ('zbor', models.ManyToManyField(to='Aeroport.zbor')),
            ],
        ),
        migrations.CreateModel(
            name='BiletedeAvion',
            fields=[
                ('id_bilet', models.AutoField(primary_key=True, serialize=False)),
                ('nume_prenume', models.CharField(max_length=50)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loc', models.CharField(max_length=10)),
                ('zbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeroport.zbor')),
            ],
        ),
    ]
