# Generated by Django 5.1.1 on 2024-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biletedeavion',
            name='pret',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
