# Generated by Django 5.1.1 on 2024-11-28 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0006_alter_customuser_data_nastere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nastere',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
