# Generated by Django 5.1.1 on 2024-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0010_categorie_promotie_vizualizare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizualizare',
            options={'ordering': ['-data_vizualizare']},
        ),
        migrations.AddField(
            model_name='promotie',
            name='categorii',
            field=models.ManyToManyField(to='Aeroport.categorie'),
        ),
    ]
