# Generated by Django 5.1.1 on 2024-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0011_alter_vizualizare_options_promotie_categorii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotie',
            name='categorii',
        ),
        migrations.AddField(
            model_name='promotie',
            name='destinatie',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
