# Generated by Django 5.1.1 on 2024-12-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0012_remove_promotie_categorii_promotie_destinatie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizualizare',
            name='bilet',
        ),
        migrations.AddField(
            model_name='vizualizare',
            name='zbor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Aeroport.zbor'),
        ),
    ]
