# Generated by Django 5.1.1 on 2024-12-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0013_remove_vizualizare_bilet_vizualizare_zbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biletedeavion',
            name='actualizat_la',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zbor',
            name='actualizat_la',
            field=models.DateField(auto_now=True),
        ),
    ]
