# Generated by Django 5.1.1 on 2024-12-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeroport', '0015_customuser_blocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='zbor',
            name='pret',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
